# Pandas, Matplotlib and Seaborn

In [ ]:
import pandas as pd

[Dataset Soruce](https://www.kaggle.com/datasets/rajkumarpandey02/gdp-in-usd-per-capita-income-by-country)

CONTENT
<p>The figures presented here do not take into account differences in the cost of living in different countries, and the results vary greatly from one year to another based on fluctuations in the exchange rates of the country's currency. Such fluctuations change a country's ranking from one year to the next, even though they often make little or no difference to the standard of living of its population.

GDP per capita is often considered an indicator of a country's standard of living; however, this is inaccurate because GDP per capita is not a measure of personal income.

Comparisons of national income are also frequently made on the basis of purchasing power parity (PPP), to adjust for differences in the cost of living in different countries. (See List of countries by GDP (PPP) per capita.) PPP largely removes the exchange rate problem but not others; it does not reflect the value of economic output in international trade, and it also requires more estimation than GDP per capita. On the whole, PPP per capita figures are more narrowly spread than nominal GDP per capita figures.</p>

Here are some resources to learn about GDP:
#### [World Bank](https://data.worldbank.org/indicator/ny.gdp.pcap.cd?most_recent_value_desc=false)
#### [Our World in Data](https://ourworldindata.org/grapher/gdp-per-capita-worldbank)
#### [IMF](https://www.imf.org/external/datamapper/NGDPD@WEO/OEMDC/ADVEC/WEOWORLD)
#### [UN Data](https://data.un.org/Data.aspx?d=SNAAMA&f=grID%3A101%3BcurrID%3AUSD%3BpcFlag%3A1)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving GDP (nominal) per Capita.csv to GDP (nominal) per Capita.csv

In [ ]:
df = pd.read_csv("GDP (nominal) per Capita.csv",encoding= 'unicode_escape',  index_col=0)

## EDA (Exploratory Data Analysis)

### Use this section to explore and inspect dataset.

In [ ]:
df

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
1,Monaco,Europe,0,0,234316,2021,234317,2021
2,Liechtenstein,Europe,0,0,157755,2020,169260,2021
3,Luxembourg,Europe,132372,2023,133590,2021,133745,2021
4,Ireland,Europe,114581,2023,100172,2021,101109,2021
5,Bermuda,Americas,0,0,114090,2021,112653,2021
...,...,...,...,...,...,...,...,...
219,Malawi,Africa,496,2023,635,2021,613,2021
220,South Sudan,Africa,467,2023,1072,2015,400,2021
221,Sierra Leone,Africa,415,2023,480,2021,505,2021
222,Afghanistan,Asia,611,2020,369,2021,373,2021
223,Burundi,Africa,249,2023,222,2021,311,2021

In [ ]:
df.head()

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
1,Monaco,Europe,0,0,234316,2021,234317,2021
2,Liechtenstein,Europe,0,0,157755,2020,169260,2021
3,Luxembourg,Europe,132372,2023,133590,2021,133745,2021
4,Ireland,Europe,114581,2023,100172,2021,101109,2021
5,Bermuda,Americas,0,0,114090,2021,112653,2021

In [ ]:
df.tail()

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
219,Malawi,Africa,496,2023,635,2021,613,2021
220,South Sudan,Africa,467,2023,1072,2015,400,2021
221,Sierra Leone,Africa,415,2023,480,2021,505,2021
222,Afghanistan,Asia,611,2020,369,2021,373,2021
223,Burundi,Africa,249,2023,222,2021,311,2021

In [ ]:
df.shape

(223, 8)

In [ ]:
df.columns

Index(['Country/Territory', 'UN_Region', 'IMF_Estimate', 'IMF_Year',
       'WorldBank_Estimate', 'WorldBank_Year', 'UN_Estimate', 'UN_Year'],
      dtype='object')

In [ ]:
df.isnull().values.any(axis=1)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [ ]:
df.isnull().sum()

Country/Territory     0
UN_Region             0
IMF_Estimate          0
IMF_Year              0
WorldBank_Estimate    0
WorldBank_Year        0
UN_Estimate           0
UN_Year               0
dtype: int64

In [ ]:
df.isnull().values.any()

np.False_

In [ ]:
# number of countries per region

In [ ]:
df.UN_Region.value_counts()

UN_Region
Africa      55
Asia        51
Americas    48
Europe      48
Oceania     20
World        1
Name: count, dtype: int64

In [ ]:
#What is European Union[n 1]?

In [ ]:
df[df['Country/Territory'] == 'European Union[n 1]']

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
36,European Union[n 1],Europe,39940,2023,38411,2021,31875,2021

In [ ]:
# Countries in Europe below avarege

In [ ]:
df[df['IMF_Estimate'] < df['IMF_Estimate'].mean()]

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
1,Monaco,Europe,0,0,234316,2021,234317,2021
2,Liechtenstein,Europe,0,0,157755,2020,169260,2021
5,Bermuda,Americas,0,0,114090,2021,112653,2021
9,Isle of Man,Europe,0,0,87158,2019,0,0
10,Cayman Islands,Americas,0,0,86569,2021,85250,2021
...,...,...,...,...,...,...,...,...
219,Malawi,Africa,496,2023,635,2021,613,2021
220,South Sudan,Africa,467,2023,1072,2015,400,2021
221,Sierra Leone,Africa,415,2023,480,2021,505,2021
222,Afghanistan,Asia,611,2020,369,2021,373,2021
223,Burundi,Africa,249,2023,222,2021,311,2021

In [ ]:
# Which countries in Europe has higher GDP than UK?
df.loc[df['UN_Region'] == 'Europe', 'IMF_Estimate'].mean()

np.float64(34446.75)

## groupby()

[Learn more about groupby](https://www.geeksforgeeks.org/pandas-groupby/)

In [ ]:
df.groupby(['UN_Region'])['IMF_Estimate'].mean()

UN_Region
Africa       2802.345455
Americas    11871.041667
Asia        16665.254902
Europe      34446.750000
Oceania      9133.150000
World       13440.000000
Name: IMF_Estimate, dtype: float64

In [ ]:
df.groupby(['UN_Region'])['IMF_Estimate'].max()

UN_Region
Africa       19536
Americas     80034
Asia         91100
Europe      132372
Oceania      64964
World        13440
Name: IMF_Estimate, dtype: int64

In [ ]:
df.groupby(['UN_Region'])['IMF_Estimate'].min()

UN_Region
Africa          0
Americas        0
Asia            0
Europe          0
Oceania         0
World       13440
Name: IMF_Estimate, dtype: int64

In [ ]:
df.groupby(['UN_Region'])['IMF_Estimate'].count()

UN_Region
Africa      55
Americas    48
Asia        51
Europe      48
Oceania     20
World        1
Name: IMF_Estimate, dtype: int64

In [ ]:
df.groupby(['UN_Region'])['IMF_Estimate'].sum()

UN_Region
Africa       154129
Americas     569810
Asia         849928
Europe      1653444
Oceania      182663
World         13440
Name: IMF_Estimate, dtype: int64

In [ ]:
df.groupby(['UN_Region'])['IMF_Estimate'].median()

UN_Region
Africa       1475.0
Americas     6829.5
Asia         6180.0
Europe      27053.0
Oceania      3926.5
World       13440.0
Name: IMF_Estimate, dtype: float64

In [ ]:
df.groupby(['UN_Region'])['IMF_Estimate'].std()

UN_Region
Africa       3421.329481
Americas    15227.831902
Asia        21375.993483
Europe      31085.656917
Oceania     17001.622425
World                NaN
Name: IMF_Estimate, dtype: float64

In [ ]:
df.groupby(['UN_Region'])['IMF_Estimate'].describe()

,count,mean,std,min,25%,50%,75%,max
UN_Region,,,,,,,,
Africa,55.0,2802.345455,3421.329481,0.0,833.00,1475.0,3696.00,19536.0
Americas,48.0,11871.041667,15227.831902,0.0,1629.75,6829.5,17469.25,80034.0
Asia,51.0,16665.254902,21375.993483,0.0,2516.00,6180.0,29153.50,91100.0
Europe,48.0,34446.750000,31085.656917,0.0,10192.50,27053.0,51774.50,132372.0
Oceania,20.0,9133.150000,17001.622425,0.0,0.00,3926.5,5917.00,64964.0
World,1.0,13440.000000,NaN,13440.0,13440.00,13440.0,13440.00,13440.0

## Which countries have below average by IMF world estimate?

In [ ]:
# Which countries have below average by IMF world estimate?
df[df['IMF_Estimate'] < df['IMF_Estimate'].mean()]

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
1,Monaco,Europe,0,0,234316,2021,234317,2021
2,Liechtenstein,Europe,0,0,157755,2020,169260,2021
5,Bermuda,Americas,0,0,114090,2021,112653,2021
9,Isle of Man,Europe,0,0,87158,2019,0,0
10,Cayman Islands,Americas,0,0,86569,2021,85250,2021
...,...,...,...,...,...,...,...,...
219,Malawi,Africa,496,2023,635,2021,613,2021
220,South Sudan,Africa,467,2023,1072,2015,400,2021
221,Sierra Leone,Africa,415,2023,480,2021,505,2021
222,Afghanistan,Asia,611,2020,369,2021,373,2021
223,Burundi,Africa,249,2023,222,2021,311,2021

### IMF estimate 0 values

## Which country has highest UN Estimate?

In [ ]:
df[df['UN_Estimate'] == df['UN_Estimate'].max()]

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
1,Monaco,Europe,0,0,234316,2021,234317,2021

## Which country has highest Worlbank Estimate?

In [ ]:
df[df['WorldBank_Estimate'] == df['WorldBank_Estimate'].max()]

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
1,Monaco,Europe,0,0,234316,2021,234317,2021

In [ ]:
df.sort_values(['WorldBank_Estimate'], ascending=[False])

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
1,Monaco,Europe,0,0,234316,2021,234317,2021
2,Liechtenstein,Europe,0,0,157755,2020,169260,2021
3,Luxembourg,Europe,132372,2023,133590,2021,133745,2021
5,Bermuda,Americas,0,0,114090,2021,112653,2021
4,Ireland,Europe,114581,2023,100172,2021,101109,2021
...,...,...,...,...,...,...,...,...
46,Taiwan,Asia,33907,2023,0,0,0,0
31,British Virgin Islands,Americas,0,0,0,0,49444,2021
76,Cook Islands,Oceania,0,0,0,0,19264,2021
196,Zanzibar,Africa,0,0,0,0,1211,2021
212,North Korea,Asia,0,0,0,0,654,2021

## Which country has highest IMF Estimate?

In [ ]:
df[df['IMF_Estimate'] == df['IMF_Estimate'].max()]

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
3,Luxembourg,Europe,132372,2023,133590,2021,133745,2021

In [ ]:
df.sort_values(['IMF_Estimate'], ascending=[False])

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
3,Luxembourg,Europe,132372,2023,133590,2021,133745,2021
4,Ireland,Europe,114581,2023,100172,2021,101109,2021
6,Norway,Europe,101103,2023,89154,2021,89242,2021
7,Switzerland,Europe,98767,2023,91992,2021,93525,2021
8,Singapore,Asia,91100,2023,72794,2021,66822,2021
...,...,...,...,...,...,...,...,...
37,US Virgin Islands,Americas,0,0,39552,2020,0,0
104,Cuba,Americas,0,0,9500,2020,11255,2021
196,Zanzibar,Africa,0,0,0,0,1211,2021
204,Syria,Asia,0,0,533,2020,925,2021
212,North Korea,Asia,0,0,0,0,654,2021

## Filling 0 Values by average

In [ ]:
import numpy as np

In [ ]:
# replace 0 with null values
df = df.replace(0, np.nan)

In [ ]:
df

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
1,Monaco,Europe,NaN,NaN,234316.0,2021.0,234317.0,2021
2,Liechtenstein,Europe,NaN,NaN,157755.0,2020.0,169260.0,2021
3,Luxembourg,Europe,132372.0,2023.0,133590.0,2021.0,133745.0,2021
4,Ireland,Europe,114581.0,2023.0,100172.0,2021.0,101109.0,2021
5,Bermuda,Americas,NaN,NaN,114090.0,2021.0,112653.0,2021
...,...,...,...,...,...,...,...,...
219,Malawi,Africa,496.0,2023.0,635.0,2021.0,613.0,2021
220,South Sudan,Africa,467.0,2023.0,1072.0,2015.0,400.0,2021
221,Sierra Leone,Africa,415.0,2023.0,480.0,2021.0,505.0,2021
222,Afghanistan,Asia,611.0,2020.0,369.0,2021.0,373.0,2021
223,Burundi,Africa,249.0,2023.0,222.0,2021.0,311.0,2021

In [ ]:
# Calculate the average of 'Worldbank_Estimate' and 'UN_Estimate' columns

In [ ]:
df[['WorldBank_Estimate', 'UN_Estimate']].mean()

WorldBank_Estimate    19540.805556
UN_Estimate           18514.528037
dtype: float64

In [ ]:
# Fill the null values in 'imf' column with the calculated average

In [ ]:
df['IMF_Estimate'] = df['IMF_Estimate'].fillna(df['IMF_Estimate'].mean())
df

,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
1,Monaco,Europe,17377.736041,NaN,234316.0,2021.0,234317.0,2021
2,Liechtenstein,Europe,17377.736041,NaN,157755.0,2020.0,169260.0,2021
3,Luxembourg,Europe,132372.000000,2023.0,133590.0,2021.0,133745.0,2021
4,Ireland,Europe,114581.000000,2023.0,100172.0,2021.0,101109.0,2021
5,Bermuda,Americas,17377.736041,NaN,114090.0,2021.0,112653.0,2021
...,...,...,...,...,...,...,...,...
219,Malawi,Africa,496.000000,2023.0,635.0,2021.0,613.0,2021
220,South Sudan,Africa,467.000000,2023.0,1072.0,2015.0,400.0,2021
221,Sierra Leone,Africa,415.000000,2023.0,480.0,2021.0,505.0,2021
222,Afghanistan,Asia,611.000000,2020.0,369.0,2021.0,373.0,2021
223,Burundi,Africa,249.000000,2023.0,222.0,2021.0,311.0,2021

In [ ]:
# Drop the temporary 'avg_worldbank_un' column if not needed

[Visit this link to learn more about ffill](https://www.w3schools.com/python/pandas/ref_df_ffill.asp)

[Visit this link to learn more about bfill](https://www.w3schools.com/python/pandas/ref_df_bfill.asp)

## Checking Missing Values

## Visualization

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

### Histogram

In [ ]:
df.hist(figsize=(10,8))
plt.show()

In [ ]:
df[["IMF_Estimate", "UN_Estimate", "WorldBank_Estimate"]].hist(figsize=(12,9))

plt.show()

In [ ]:
df[["IMF_Estimate", "UN_Estimate", "WorldBank_Estimate"]].hist(bins=5, figsize=(12,9))

plt.show()

In [ ]:
df["WorldBank_Estimate"].agg(["min","max"])

In [ ]:
234316/5
#1 bin size if bins=5

In [ ]:
df[df["WorldBank_Estimate"]<=46863.2]["WorldBank_Estimate"].count()

In [ ]:
234316/10
#1 bin size if bins not given any number

In [ ]:
df[["IMF_Estimate", "UN_Estimate", "WorldBank_Estimate"]].hist(bins=3, figsize=(12,9))

plt.show()

In [ ]:
df[["IMF_Estimate", "UN_Estimate", "WorldBank_Estimate"]].hist(bins=15, figsize=(15,12))

#23400/15 = 15300
plt.show()

### Correlation Heatmap

In [ ]:
df[["IMF_Estimate", "UN_Estimate", "WorldBank_Estimate"]].corr()

In [ ]:
corr = df[["IMF_Estimate", "UN_Estimate", "WorldBank_Estimate"]].corr()

plt.figure(figsize=(9,6))
sns.heatmap(corr)

plt.show()

In [ ]:
corr = df[["IMF_Estimate", "UN_Estimate", "WorldBank_Estimate"]].corr()

plt.figure(figsize=(9,6))

sns.heatmap(corr, annot=True)

plt.show()

In [ ]:
corr = df[["IMF_Estimate", "UN_Estimate", "WorldBank_Estimate"]].corr()

plt.figure(figsize=(9,6))

sns.heatmap(corr, annot=True, fmt=".2f", cmap = 'GnBu', annot_kws={"size": 12})

plt.show()

In [ ]:
corr = df[["IMF_Estimate", "UN_Estimate", "WorldBank_Estimate"]].corr()

plt.figure(figsize=(9,6))

sns.heatmap(corr, annot=True, cmap = 'Purples')

plt.title("Correlation Map")


plt.show()

In [ ]:
corr = df.select_dtypes(include=[int, float]).corr()

plt.figure(figsize=(9,6))

sns.heatmap(corr, annot=True, cmap = 'Purples')

plt.show()

### Bar plot

In [ ]:
df.head()

In [ ]:
sns.barplot(x="UN_Region", y="WorldBank_Estimate", data=df, errorbar=None)

plt.show()

In [ ]:
sns.barplot(x="WorldBank_Estimate", y="UN_Region", data=df, errorbar=None)

plt.show()

In [ ]:
fig = plt.figure(figsize = (8,5))

ax = sns.barplot(x = "IMF_Estimate",  y = "UN_Region",
data = df, errorbar = None)

ax.bar_label(ax.containers[0])

plt.show()

In [ ]:
fig = plt.figure(figsize = (8,5))
ax = sns.barplot(x = "UN_Region",  y = "IMF_Estimate",
                 data = df, errorbar = None)

ax.bar_label(ax.containers[0])


ax.set_title("Regions by IMF Estimate")
plt.show()

### Scatter Plot

In [ ]:
df.plot(x='UN_Region', y='UN_Estimate', kind='scatter',
        figsize=(10,6),
        title="Scatter Plot")

plt.show()

### Boxplot and Outliers

![image.png](attachment:da6a7715-3b1c-4165-a2a9-4dc8ca096bd7.png)

In [ ]:
sns.boxplot(x=df["UN_Estimate"])

plt.show()

In [ ]:
df[df["UN_Estimate"]>50000].head()

In [ ]:
sns.boxplot(x=df["WorldBank_Estimate"])

plt.show()

In [ ]:
sns.boxplot(x=df["IMF_Estimate"])

plt.show()

In [ ]:
df[df["UN_Estimate"]>100000]

In [ ]:
df.UN_Estimate.mean()

In [ ]:
df.shape

## Create another dataframe called data excluding  5 countries with highest UN estimate

In [ ]:
data = df[-(df["UN_Estimate"]>100000)]

In [ ]:
data.head()

In [ ]:
data.shape

In [ ]:
data.UN_Estimate.mean()

In [ ]:
df.UN_Estimate.mean()

![image.png](attachment:image.png)

In [ ]:
sns.boxplot(x=data["UN_Estimate"])
plt.show()

## Removing outliers

![image.png](attachment:da6a7715-3b1c-4165-a2a9-4dc8ca096bd7.png)

![image.png](attachment:image.png)

In [ ]:
lower_q = df["UN_Estimate"].quantile(0.25)
lower_q

In [ ]:
higher_q = df["UN_Estimate"].quantile(0.75)
higher_q

In [ ]:
iqr = higher_q - lower_q
iqr

In [ ]:
upper_boundary = higher_q + 1.5 * iqr
upper_boundary

In [ ]:
lower_boundary = lower_q - 1.5 * iqr
lower_boundary

In [ ]:
df_filtered = df[(df["UN_Estimate"] < upper_boundary) & (df["UN_Estimate"] > lower_boundary)]

In [ ]:
df_filtered.head()

In [ ]:
df_filtered.shape
# there were 223 rows - 196 = 27 outliers dropped

In [ ]:
df_filtered.UN_Estimate.mean()

In [ ]:
df.UN_Estimate.mean()

In [ ]:
#how can we create a table with following
df_filtered.WorldBank_Estimate.mean()

In [ ]:
df.WorldBank_Estimate.mean()

In [ ]:
df_filtered.IMF_Estimate.mean()

In [ ]:
df.IMF_Estimate.mean()